# Generated by Django 4.1.3 on 2022-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_juicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juicing',
            name='date',
            field=models.DateField(verbose_name='Juicing Date'),
        ),
    ]
