# Generated by Django 4.1.3 on 2022-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_juicing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='juicing',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='alkaline',
            name='fruits',
            field=models.ManyToManyField(to='main_app.fruit'),
        ),
    ]
